function axes_h = custom_plotPerfSeparation(output, z, dir_saveResults, varargin)
% custom_plotSeparability - visualizes the results of a performance metric
% prediction (e.g. by oscillatory SPoC components) and the true measured
% labels.
% The function returns two figures that can be accessed independently.
%
% Synopsis
%  custom_plotSeparability(output, z, dir_saveResults, varargin)
%
% Arguments: 
%   output : struct generated by the function custom_spoc() containing all
%   the results and parameter settings from a SPoC analysis on a single 
%   parameter setting
%   z: target variable
%   dir_saveResults: directory for saving the figure
%
% Options:
%   saveToFile: optional flag to save the plots to a file
%   prctile: chooses a percentile of the data (e.g. 20% highest and lowest
%   values of target variable z)
%   metricLabel: define the label of the target variable (e.g. RT (ms))
%   legend: specifies the legend of the separability plot
%   colormapFolds: specifies the colormap that is used to shade the fold
%   division
%
% Returns:
%   -
%
%
% Andreas Meinel, May 2015

%% Setting up the default values 

def_saveToFile = false; % saves the figures to file
% def_figFlags = [1 1]; % flags to en- or disable the two figures
def_prctile = 20; % determines the percentile of e.g. fast. vs. slow RTs 
def_metricLabel = 'RT (ms)';
def_legend = {'high','low','high,est','low,est'};
% def_idxFolds = []; % vector. [nfolds, nsamples] Shading the area of the trials corresponding to each of the subplots
def_zScaling = 1; % factor scaling up the target variable (if the target variable is too small, the distribution fits don't work)
def_figSize = [800,550];
def_lineWidth = 2;
def_showTitle = 1;
def_fontSize = 16;
def_legPos = [1 1 1 1];
def_txt4Title = '';
def_xScale = 0;

p = inputParser;

addParamValue(p,'saveToFile', def_saveToFile);
% addParamValue(p,'figFlags', def_figFlags);
addParamValue(p,'prctile', def_prctile);
addParamValue(p,'metricLabel', def_metricLabel);
addParamValue(p,'legend', def_legend);
% addParamValue(p,'idxFolds',def_idxFolds);
addParamValue(p,'zScaling',def_zScaling);
addParamValue(p,'figSize',def_figSize);
addParamValue(p,'lineWidth',def_lineWidth);
addParamValue(p,'showTitle',def_showTitle);
addParamValue(p,'fontSize',def_fontSize);
addParamValue(p,'legPos',def_legPos);
addParamValue(p,'txt4Title',def_txt4Title);
addParamValue(p,'xScale',def_xScale);

parse(p,varargin{:})
options = p.Results;


%% Extracting the SPoC results 

params = output.params;
out = output.out;
z_est = zscore(out.z_est);

%% Fig.1: Prediction accuracy

axes_h = gca;
axes(axes_h);
set(gca,'FontSize',options.fontSize)
set(gcf, 'Position', [200 200 options.figSize])

% figh = figure('Units','points','position',[200, 200, options.figSize]);

% scale up the target variable (required if e.g. z is between -2 and 2 =>
% the distribution fits don't work properly)
z_est = options.zScaling*z_est;
z = options.zScaling*z;

% get high/low performance percentiles according to true z

Y_true = prctile(z,[options.prctile,100-options.prctile]);
%     Y_true = prctile(z,[20,80]);
idx_slow = find(z<Y_true(1));
idx_fast = find(z>Y_true(2));

z_slow = z(idx_slow);
z_fast = z(idx_fast);

x_dist = ((1-0.1*sign(min(z)))*round(min(z))):((1+0.1*sign(max(z)))*round(max(z)));
pd_slow=fitdist(z_slow','Kernel','Kernel','normal');
z_distSlow = pdf(pd_slow,x_dist);
pd_fast=fitdist(z_fast','Kernel','Kernel','normal');
z_distFast = pdf(pd_fast,x_dist);

% get high/low performance percentiles of z according to prediction z_est

Y_est = prctile(z_est,[options.prctile,100-options.prctile]);
idx_slow2 = find(z_est<Y_est(1));
idx_fast2 = find(z_est>Y_est(2));

% extracting low & high performance trials of true z distribution according 
% to percentiles of the prediction distribution
z_slow_est = z(idx_slow2);
z_fast_est = z(idx_fast2);

pd_slow2=fitdist(z_slow_est','Kernel','Kernel','normal');
z_distSlow2 = pdf(pd_slow2,x_dist);
pd_fast2=fitdist(z_fast_est','Kernel','Kernel','normal');
z_distFast2 = pdf(pd_fast2,x_dist);

l(1) = plot(x_dist,z_distSlow,'--','LineWidth',options.lineWidth,'Color',[1,.5,0]); hold on;
l(2) = plot(x_dist,z_distFast,'--','LineWidth',options.lineWidth,'Color',[0,0.8,0.3]); hold on;
l(3) = plot(x_dist,z_distSlow2,'LineWidth',options.lineWidth,'Color',[1,.5,0]); hold on;
l(4) = plot(x_dist,z_distFast2,'LineWidth',options.lineWidth,'Color',[0,0.8,0.3]); 
% set(gca, 'FontSize', options.fontSize)
if options.showTitle
    if ~isempty(options.txt4Title)
        title(options.txt4Title)
    else
        title([num2str(options.prctile),' percentiles'])
    end    
end
grid on
axis on
set(gca,'YTick',[])
h = legend(l,options.legend,'Location','NorthEast');
set(h,'Position',options.legPos,'Units','normalized');
ylabel('pdf (a.u.)')

if options.xScale
    xlim([min(x_dist),max(x_dist)])
end
if options.zScaling > 1
    xlabel([num2str(options.zScaling),'\cdot',options.metricLabel])
else
    xlabel(options.metricLabel)
end
  
    
%     dist_figh = figure; 
%     n_folds = 5;
%     n_epos = length(z);
%     [divTr, divTe] = sample_chronKFold(ones(1,n_epos), n_folds);
%     
%     for j = 1:n_folds
%         z_mapFold = z(divTe{1}{j});
%         z_estFold = z_est(divTe{1}{j});
%         
%         switch sign(output.xval_corr(j))
%             case 1
%                 [z_estSorted, idx] = sort(z_estFold,'ascend');
%             case -1
%                 [z_estSorted, idx] = sort(z_estFold,'descend');
%                 disp('aqui');
%         end
%         z_mapSorted = z(idx);
%         
%         x_dist = 100:900;
%         fit = z_mapSorted(round(end/2):end);
%         pd=fitdist(fit(randperm(length(fit)))','Kernel','Kernel','normal');
%         z_distAll(j,:) = pdf(pd,x_dist);
%         fit = z_mapSorted(1:round(end/2));
%         pd=fitdist(fit(randperm(length(fit)))','Kernel','Kernel','normal');
%         z_distBest(j,:) = pdf(pd,x_dist);
%         
%     end
    
if options.saveToFile
    fband_str =  strjoin(strsplit(num2str(params.band,'%.0f %.0f')),'-');
    ival_str = strjoin(strsplit(num2str(int32(params.ival))),'-');
    fband_str(fband_str == '.') = 'p';
    savepic([dir_saveResults,'_zSeparation_',params.mfctName,'_', ...
        'ival[',ival_str ,']','_','fband[',fband_str,']'], 'pdf');
    close all
end
           
end
